### ISSUE TITLE
Error message not going away

### ISSUE THREAD

**Issue by haggins** [etherparty/explorer#10]
I want to use this explorer at my private dev network. However, I'm not able to get rid of the error message 

> geth --rpc --rpccorsdomain "http://localhost:8000"

Do I have any geth argument which might prevent this explorer to connect?

`./geth --identity "DevNode" --genesis ~/git/eth/dev/custom_genesis.json --rpc --rpcport "8102" --rpccorsdomain "http://localhost:8000" --datadir "~/git/eth/data/" --port "30301" --nodiscover --ipcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpcapi "db,eth,net,web3" --autodag --networkid 7682878 --nat "any" --dev --ipcpath "~/.ethereum/geth.ipc" --mine --minerthreads=1 --unlock 0x69B7900537449e862c19aAF1D08b648e76629EBa console`

Kind regards,
haggins

**Comment by whitj00** [comment]
You’re using a nonstandard rpc port (8102) so it won’t connect correctly.  If you want to use 8102 you can change the source code to use that port.

**Comment by haggins** [comment]
Wow, thanks for this lightning fast answer! It works :+1:
