### ISSUE TITLE
Implement lazy loading

### ISSUE THREAD

**Issue by ethernomad** [etherparty/explorer#19]
If the explorer is communicating with a remote node, it can take a really long time for the front page to load as there are multiple requests for each block.

It would be really great if the page was populated as the data came in instead of waiting for all of it.

**Comment by whitj00** [comment]
Hi,

This explorer isn't really optimized to work with remote nodes well.  I believe there are forks that are more up to date and would be best for this.  If I have time I'll see if I can work on that
