### ISSUE TITLE
What should i do if i want to watch this page from other computers in a same  local area network

### ISSUE THREAD

**Issue by soy-sauce-rice** [etherparty/explorer#32]
sorry ,my English is not good.
I changed "localhost" to "0.0.0.0" in the file explorer/package.json
and change  ' --rpccorsdomain "localhost:8000" ' to '--rpccorsdomain "http://192.168.1.105:8000"'.
"192.168.1.105" is  ip of  the computer which running geth
 When i input "192.168.1.105:8000" on the computer which running geth , it is done,
but if i input "192.168.1.105:8000" on another ,it return "allow access to geth and refresh the page"
so , what should i do if i want successful watch this page from other computers?

**Comment by 6hundred** [comment]
modify app.json like below
 var eth_node_url = 'http://0.0.0.0:8545'; // TODO: remote URL
the error should go away. report back what u see.
