### ISSUE TITLE
crashed when open the page

### ISSUE THREAD

**Issue by seanxlliu** [etherparty/explorer#45]
Please refer to the following detailed call stacks. Any suggestions?

Starting up http-server, serving ./app on port: 8000
Hit CTRL-C to stop the server
[Wed, 28 Mar 2018 04:02:30 GMT] "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
_http_outgoing.js:348
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at ResponseStream.(anonymous function) [as setHeader] (C:\Code\bc\explorer\node_modules\union\lib\response-stream.js:86:34)
    at serve (C:\Code\bc\explorer\node_modules\ecstatic\lib\ecstatic.js:146:11)
    at C:\Code\bc\explorer\node_modules\ecstatic\lib\ecstatic.js:139:9
    at FSReqWrap.oncomplete (fs.js:117:15)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Xiaolu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! EthereumExplorer@0.1.0 start: `http-server ./app -a localhost -p 8000 -c-1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EthereumExplorer@0.1.0 start script 'http-server ./app -a localhost -p 8000 -c-1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the EthereumExplorer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server ./app -a localhost -p 8000 -c-1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs EthereumExplorer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls EthereumExplorer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Code\bc\explorer\npm-debug.log

**Comment by Hamdi-G** [comment]
`npm install -g http-server` should fix the problem :)

**Comment by xwEric** [comment]
same problem，I tried `npm install -g http-server`, but not work
