### ISSUE TITLE
Run Public Site Without Exposing 8545

### ISSUE THREAD

**Issue by stone212** [etherparty/explorer#49]
What would need to be changed in the settings or the code to make the app handle its RPC calls internally and now expost them to the WebUI?

I want to run this as a public blockchain explorer but don't want to expose my RPC port publicly.  (I assume that rpccors is supposed to protect it but that seems like a small barrier).

**Comment by DottoreM** [comment]
is there any information on this?

**Comment by stone212** [comment]
@DottoreM I actually use https://github.com/gobitfly/etherchain-light now but can you tell me why the RPC has to be exposed?  Maybe you can run Parity with the default of only exposing RPC to localhost?  And maybe run a reverse proxy on port 8000 for the actual explorer?

Closing because I can not help de-bug.

**Comment by DottoreM** [comment]
Apologies for re-opening. Can you tell me how I can reach you? I want to reply to your questions and talk to you.

cheers.

**Comment by stone212** [comment]
@DottoreM  You could send your PGP key or other contact info or contact me on gitter but I don't check that often.
