### ISSUE TITLE
TypeError('The header content contains invalid characters')

### ISSUE THREAD

**Issue by peer2peer** [etherparty/explorer#52]
> EthereumExplorer@0.1.0 start F:\explorer
> http-server ./app -a localhost -p 8000 -c-1

Starting up http-server, serving ./app on port: 8000
Hit CTRL-C to stop the server
[Tue, 18 Sep 2018 03:53:15 GMT] "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
_http_outgoing.js:497
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:497:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at module.exports.ResponseStream.(anonymous function) [as setHeader] (F:\explorer\node_modules\union\lib\response-stream.js:86:34)
    at serve (F:\explorer\node_modules\ecstatic\lib\ecstatic.js:146:11)
    at F:\explorer\node_modules\ecstatic\lib\ecstatic.js:139:9
    at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EthereumExplorer@0.1.0 start: `http-server ./app -a localhost -p 8000 -c-1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EthereumExplorer@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by peer2peer** [comment]
Fixed by commit 
 https://github.com/etherparty/explorer/commit/2f3819ae322f338ad7ffa1796f330903c5d41bc8

**Comment by fanyufan** [comment]
change http-server version to "^0.9.0" in package.json. it works ok for me.
