### ISSUE TITLE
list (latest) transactions/blocks

### ISSUE THREAD

**Issue by promethe42** [etherparty/explorer#6]
Hello,

any plans to list the latest transactions/blocks on the home page (for example) ?

Regards,

**Comment by whitj00** [comment]
i don't plan to, if someone submitter a PR I would.  I think it has been privately forked to support it

**Comment by promethe42** [comment]
Any idea where that fork is?

**Comment by whitj00** [comment]
Don't think it's open source

**Comment by whitj00** [comment]
done
