### ISSUE TITLE
can I use to allow anyone explore my own testnet chain?

### ISSUE THREAD

**Issue by maximilianh** [etherparty/explorer#9]
Maybe I'm misunderstanding something, but it seems that opening the RPC to all the internet is not such a good idea... can I use etherparty to allow anyone to browse my own testnet? Or do I need a different software for that...?

**Comment by whitj00** [comment]
and yes, you can use this to browse any chain using ethereums api

**Comment by whitj00** [comment]
This is meant to be a client side application.  The geth command that is given only opens up RPC access to only this website (though this is not very secure, you shouldn’t unlock your account when you enable RPC to the public)

**Comment by maximilianh** [comment]
I'll try it. Thanks for your quick reply! 

It seems this is the only open-source block chain browser. As you know, for all people that run private testnets, something like etherscan.io a browser is very useful for debugging.  I'm surprised there are not more tools like this one...
